#! /usr/bin/env node
const { program } = require('commander')

// 定义命令和选项
program
  .command('init')
  .version('1.0.0', '-v, --version')
  .description('初始化commander小工具')
  .option('-u, --username <username>', '你的名字')
  .option('-c, --color <color>', '你喜欢的颜色')
  .option('-a, --age <age>', '你的年龄')
  .action(function (res) {
    // console.log('res', res)
  })
  .parse(process.argv)

// 执行相应的操作
