#! /usr/bin/env node

const { program } = require('commander')
const inquirer = require('inquirer')
const simpleGit = require('simple-git')


const handleVueTemplate = () => {
    const vueQuestions = [
        {
            type: 'list',
            name: 'vueVersion',
            choices: ['vue3', 'vue2'],
            message: '选择vue版本'
        },
        {
            type: 'list',
            name: 'compileType',
            choices: ['vite', 'webpack'],
            message: '选择编译工具'
        },
        {
            type: 'list',
            name: 'installType',
            choices: ['npm', 'pnpm', 'yarn'],
            message: '选择安装工具'
        },
    ]

    inquirer.prompt(vueQuestions).then(answsers => {
        simpleGit('https://github.com/vuejs-templates/simple.git')
        console.log('djch answsers', answsers)
    }).catch(err => console.log('djch err', err))
}

program
    .command('create')
    .description('初始化脚手架')
    .version('1.0.0')
    .action(function (argv, opts, cmd) {
        // argv 使整个process上的对象
        // opts 是当前脚本的参数，比如 ./dume crate vue -> ['create', 'vue'] 是个数组
        // cmd 
        const [actionName, frameName] = opts || []

        if (actionName === 'create') {
            switch(frameName) {
                case 'vue':
                    handleVueTemplate()
                    // 弹出vue相关的模版选项
                    break;
            }
        }
        // console.log('djch ', opts, cmd)
    })
    .parse(process.argv)